version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: email-sender-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: email_sender
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: email-sender-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  api-service:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: email-sender-api
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=email_sender
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped

  web-app:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: email-sender-web
    ports:
      - "3001:80"
    restart: unless-stopped

  worker-service:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    container_name: email-sender-worker
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=email_sender
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
