version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: email-sender-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: email_sender
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: email-sender-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  api-service:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    env_file:
      - ./packages/api-service/.env
    container_name: email-sender-api
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    restart: unless-stopped

  web-app:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - ./packages/web-app/.env
    container_name: email-sender-web
    ports:
      - "3001:80"
    restart: unless-stopped

  worker-service:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    env_file:
      - ./packages/worker-service/.env
    container_name: email-sender-worker
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
